// main.cpp — virtual-ac3-encoder engine entry point.
//
// Wires capture -> ring buffer -> AC3/IEC61937 passthrough and now also owns a small
// persistent runtime control plane:
//   * SURROUND mode: normal VB-CABLE -> AC3 -> exclusive S/PDIF pipeline
//   * GUITAR mode:   destroys the WASAPI pipeline and releases S/PDIF for ASIO4ALL
//
// Control commands (sent to the already-running background engine):
//   engine.exe --mode surround
//   engine.exe --mode guitar
//   engine.exe --mode status
//
// Native two-button controller:
//   engine.exe --switcher
//
#include "ComUtil.h"
#include "Config.h"
#include "DeviceEnum.h"
#include "ModeControl.h"
#include "RingBuffer.h"
#include "WasapiCapture.h"
#include "WasapiPassthrough.h"

#include <atomic>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <memory>
#include <mutex>
#include <string>
#include <thread>

#include "Version.h" // generated by CMake; defines VAC3_VERSION
#ifndef VAC3_VERSION
#define VAC3_VERSION "0.0.0-dev"
#endif

static std::atomic_bool g_stop{false};

static BOOL WINAPI CtrlHandler(DWORD type)
{
  if (type == CTRL_C_EVENT || type == CTRL_BREAK_EVENT || type == CTRL_CLOSE_EVENT)
  {
    g_stop.store(true);
    return TRUE;
  }
  return FALSE;
}

static std::string ExeDir()
{
  char buf[MAX_PATH] = {0};
  DWORD n = GetModuleFileNameA(nullptr, buf, MAX_PATH);
  std::string p(buf, n);
  size_t slash = p.find_last_of("\\/");
  return slash == std::string::npos ? std::string(".") : p.substr(0, slash);
}

static std::string Trim(const std::string& s)
{
  size_t a = s.find_first_not_of(" \t\r\n");
  size_t b = s.find_last_not_of(" \t\r\n");
  return a == std::string::npos ? std::string() : s.substr(a, b - a + 1);
}

// Load a key=value config file (# or ; comments). CLI args override these.
// Keys: in, in_id, out, out_id, bitrate, safe, loopback, out_spdif, upmix,
//       layout, auto_threshold_db, auto_hold_ms.
static void LoadConfigFile(const std::string& path, Config& c)
{
  std::ifstream f(path);
  if (!f) return;
  std::string line;
  while (std::getline(f, line))
  {
    std::string s = Trim(line);
    if (s.empty() || s[0] == '#' || s[0] == ';') continue;
    size_t eq = s.find('=');
    if (eq == std::string::npos) continue;
    std::string k = Trim(s.substr(0, eq));
    std::string v = Trim(s.substr(eq + 1));
    auto truthy = [](const std::string& x) { return x == "1" || x == "true" || x == "yes"; };
    if      (k == "in")                c.inName = Widen(v.c_str());
    else if (k == "in_id")             c.inId = Widen(v.c_str());
    else if (k == "out")               c.outName = Widen(v.c_str());
    else if (k == "out_id")            c.outId = Widen(v.c_str());
    else if (k == "bitrate")           c.bitRate = std::strtoll(v.c_str(), nullptr, 10);
    else if (k == "safe")              c.safeFrames = (uint32_t)std::strtoul(v.c_str(), nullptr, 10);
    else if (k == "loopback")          c.loopback = truthy(v);
    else if (k == "out_spdif")         c.outAutoSpdif = truthy(v);
    else if (k == "upmix")             c.upmix = v;
    else if (k == "layout")            c.layout = v;
    else if (k == "auto_threshold_db") c.autoThresholdDb = std::strtod(v.c_str(), nullptr);
    else if (k == "auto_hold_ms")      c.autoHoldMs = (uint32_t)std::strtoul(v.c_str(), nullptr, 10);
  }
  std::printf("Loaded config: %s\n", path.c_str());
}

static void ParseArgs(int argc, char** argv, Config& c)
{
  for (int i = 1; i < argc; ++i)
  {
    std::string a = argv[i];
    auto next = [&]() -> std::wstring { return (i + 1 < argc) ? Widen(argv[++i]) : std::wstring(); };
    if (a == "--config")          { if (i + 1 < argc) ++i; } // handled before ParseArgs
    else if (a == "--hidden")     {}                          // handled in the pre-scan
    else if (a == "--log")        { if (i + 1 < argc) ++i; }  // handled in the pre-scan
    else if (a == "--version" || a == "-v") {}                // handled in the pre-scan
    else if (a == "--list")       c.listDevices = true;
    else if (a == "--probe")      c.probe = true;
    else if (a == "--loopback")   c.loopback = true;
    else if (a == "--mon")        c.monitor = true;
    else if (a == "--duration" && i + 1 < argc)
      c.durationSeconds = (int)std::strtol(argv[++i], nullptr, 10);
    else if (a == "--in")         c.inName = next();
    else if (a == "--in-id")      c.inId = next();
    else if (a == "--out")        c.outName = next();
    else if (a == "--out-id")     c.outId = next();
    else if (a == "--out-spdif")  c.outAutoSpdif = true;
    else if (a == "--bitrate" && i + 1 < argc)
      c.bitRate = std::strtoll(argv[++i], nullptr, 10);
    else if (a == "--safe" && i + 1 < argc)
      c.safeFrames = (uint32_t)std::strtoul(argv[++i], nullptr, 10);
    else if (a == "--upmix" && i + 1 < argc)
      c.upmix = argv[++i];
    else if (a == "--layout" && i + 1 < argc)
      c.layout = argv[++i];
    else if (a == "--auto-threshold-db" && i + 1 < argc)
      c.autoThresholdDb = std::strtod(argv[++i], nullptr);
    else if (a == "--auto-hold-ms" && i + 1 < argc)
      c.autoHoldMs = (uint32_t)std::strtoul(argv[++i], nullptr, 10);
    else
      std::fprintf(stderr, "ignoring unknown arg: %s\n", a.c_str());
  }
}

static bool ResolveCapture(const Config& c, ComPtr<IMMDevice>& dev, EndpointInfo& info)
{
  const EDataFlow flow = c.loopback ? eRender : eCapture;
  if (!c.inId.empty())
  {
    if (!DeviceEnum::GetById(c.inId, dev))
    {
      std::fprintf(stderr, "input id not found\n");
      return false;
    }
    info.id = c.inId;
    return true;
  }
  if (DeviceEnum::FindByNameSubstring(flow, c.inName, dev, info))
    return true;
  std::fprintf(stderr, "input device matching \"%s\" not found among %s endpoints (try --list)\n",
               Narrow(c.inName.c_str()).c_str(), c.loopback ? "render" : "capture");
  return false;
}

static bool ResolveOutput(const Config& c, ComPtr<IMMDevice>& dev, EndpointInfo& info)
{
  if (!c.outId.empty())
  {
    if (!DeviceEnum::GetById(c.outId, dev))
    {
      std::fprintf(stderr, "output id not found\n");
      return false;
    }
    info.id = c.outId;
    return true;
  }
  if (!c.outName.empty())
  {
    if (DeviceEnum::FindByNameSubstring(eRender, c.outName, dev, info))
      return true;
    std::fprintf(stderr, "output device matching \"%s\" not found (try --list)\n",
                 Narrow(c.outName.c_str()).c_str());
    return false;
  }
  if (c.outAutoSpdif)
  {
    for (const auto& e : DeviceEnum::List(eRender))
      if (e.isSpdif)
      {
        info = e;
        return DeviceEnum::GetById(e.id, dev);
      }
    std::fprintf(stderr, "no SPDIF output endpoint found (try --list / --out)\n");
    return false;
  }
  std::fprintf(stderr, "no output specified; use --out, --out-id or --out-spdif (or --list)\n");
  return false;
}

// Capture-only diagnostic: report how much audio is flowing from the input. Non-intrusive
// (shared-mode capture/loopback; does not touch the optical output).
static int RunMonitor(const Config& c, IMMDevice* inDev)
{
  WasapiCapture cap;
  if (!cap.Init(inDev, c.loopback)) return 1;
  const CaptureFormat& f = cap.Format();
  const size_t bpf = f.bytesPerFrame() ? f.bytesPerFrame() : 1;
  RingBuffer ring(static_cast<size_t>(32) * 1536 * bpf);
  cap.SetRing(&ring);
  if (!cap.Start()) return 1;

  std::printf("Monitoring input for %d s (play something / Ctrl+C to stop)...\n", c.monitorSeconds);
  unsigned long long totalFrames = 0;
  for (int i = 0; i < c.monitorSeconds * 10 && !g_stop.load(); ++i)
  {
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    const size_t avail = ring.BytesAvailable();
    ring.Discard(avail);
    totalFrames += avail / bpf;
  }
  cap.Stop();

  const double secs = c.monitorSeconds > 0 ? c.monitorSeconds : 1;
  std::printf("Captured ~%llu frames (~%.0f frames/s; endpoint rate %u Hz). %s\n", totalFrames,
              totalFrames / secs, f.sampleRate,
              totalFrames > 0 ? "OK: audio is flowing." : "No data (silent / nothing playing to it).");
  return 0;
}

struct RunningPipeline
{
  std::unique_ptr<RingBuffer> ring;
  std::unique_ptr<WasapiCapture> capture;
  std::unique_ptr<WasapiPassthrough> output;

  ~RunningPipeline()
  {
    Stop();
  }

  void Stop()
  {
    if (capture) capture->Stop();
    if (output) output->Stop();

    // Destruction is intentional here. Stop() alone leaves IAudioClient/IMMDevice COM references
    // alive; destroying the objects fully releases exclusive S/PDIF ownership for ASIO4ALL.
    output.reset();
    capture.reset();
    ring.reset();
  }
};

static std::unique_ptr<RunningPipeline> StartAudioPipeline(const Config& cfg, std::string& error)
{
  error.clear();

  ComPtr<IMMDevice> inDev;
  EndpointInfo inInfo;
  if (!ResolveCapture(cfg, inDev, inInfo))
  {
    error = "input endpoint not found";
    return nullptr;
  }

  ComPtr<IMMDevice> outDev;
  EndpointInfo outInfo;
  if (!ResolveOutput(cfg, outDev, outInfo))
  {
    error = "S/PDIF output endpoint not found";
    return nullptr;
  }

  std::printf("Input   : %s %s\n", Narrow(inInfo.name.c_str()).c_str(),
              cfg.loopback ? "(loopback)" : "(capture)");
  std::printf("Output  : %s %s\n", Narrow(outInfo.name.c_str()).c_str(),
              outInfo.isSpdif ? "[SPDIF]" : "");

  auto p = std::make_unique<RunningPipeline>();
  p->capture = std::make_unique<WasapiCapture>();
  if (!p->capture->Init(inDev.Get(), cfg.loopback))
  {
    error = "failed to initialize capture endpoint";
    return nullptr;
  }

  const CaptureFormat cf = p->capture->Format();
  const size_t ringBytes = static_cast<size_t>(8) * 1536 * cf.bytesPerFrame();
  p->ring = std::make_unique<RingBuffer>(ringBytes);
  p->capture->SetRing(p->ring.get());

  WasapiPassthrough::Params pp;
  pp.bitRate = cfg.bitRate;
  pp.safeFrames = cfg.safeFrames;
  pp.upmixSurround = (cfg.upmix == "surround");
  pp.autoLayout = (cfg.layout == "auto");
  pp.autoThresholdDb = cfg.autoThresholdDb;
  pp.autoHoldMs = cfg.autoHoldMs;

  std::printf("Layout  : %s", pp.autoLayout ? "auto 2.0/5.1" : "fixed 5.1");
  if (pp.autoLayout)
    std::printf(" (threshold %.1f dBFS, hold %u ms)", pp.autoThresholdDb, pp.autoHoldMs);
  std::printf("\n");

  p->output = std::make_unique<WasapiPassthrough>();
  if (!p->output->Init(outDev.Get(), p->ring.get(), cf, pp))
  {
    error = "failed to acquire S/PDIF for AC-3 passthrough (device may be busy)";
    return nullptr;
  }

  if (!p->output->Start())
  {
    error = "failed to start S/PDIF passthrough";
    return nullptr;
  }

  if (!p->capture->Start())
  {
    p->output->Stop();
    error = "failed to start capture";
    return nullptr;
  }

  return p;
}

static bool HandleControllerCommandLine(int argc, char** argv)
{
  for (int i = 1; i < argc; ++i)
  {
    std::string a = argv[i];

    if (a == "--switcher")
    {
      std::exit(RunModeSwitcherGui());
    }

    if (a == "--mode" && i + 1 < argc)
    {
      const std::string command = argv[i + 1];
      if (command != "surround" && command != "guitar" && command != "status")
      {
        std::fprintf(stderr, "invalid --mode value \"%s\"; expected surround, guitar, or status\n",
                     command.c_str());
        std::exit(2);
      }

      std::string response;
      if (!SendModeCommand(command, response, 1500))
      {
        std::fprintf(stderr, "background engine is not reachable\n");
        std::exit(3);
      }

      std::printf("%s\n", response.c_str());
      std::exit(response.rfind("error:", 0) == 0 ? 1 : 0);
    }
  }
  return false;
}

int main(int argc, char** argv)
{
  for (int i = 1; i < argc; ++i)
    if (std::string(argv[i]) == "--version" || std::string(argv[i]) == "-v")
    {
      std::printf("virtual-ac3-encoder %s\n", VAC3_VERSION);
      return 0;
    }

  HandleControllerCommandLine(argc, argv);

  // Pre-scan for --log / --hidden so they apply before any output or device work.
  for (int i = 1; i < argc; ++i)
  {
    std::string a = argv[i];
    if (a == "--hidden")
    {
      HWND con = GetConsoleWindow();
      if (con) ShowWindow(con, SW_HIDE);
    }
    else if (a == "--log" && i + 1 < argc)
    {
      FILE* fp = std::freopen(argv[i + 1], "a", stdout);
      (void)fp;
      std::freopen(argv[i + 1], "a", stderr);
    }
  }
  setvbuf(stdout, nullptr, _IONBF, 0);
  std::printf("virtual-ac3-encoder %s\n", VAC3_VERSION);

  ComApartment com;
  if (!com.ok())
  {
    std::fprintf(stderr, "CoInitializeEx failed\n");
    return 1;
  }

  Config cfg;
  std::string cfgPath = ExeDir() + "\\virtual-ac3-encoder.conf";
  for (int i = 1; i + 1 < argc; ++i)
    if (std::string(argv[i]) == "--config")
      cfgPath = argv[i + 1];
  LoadConfigFile(cfgPath, cfg);
  ParseArgs(argc, argv, cfg);

  if (cfg.layout != "auto" && cfg.layout != "5.1")
  {
    std::fprintf(stderr, "invalid layout \"%s\"; expected auto or 5.1\n", cfg.layout.c_str());
    return 1;
  }

  if (cfg.listDevices)
  {
    std::printf("Render (output) endpoints:\n");
    DeviceEnum::Print(DeviceEnum::List(eRender));
    std::printf("\nCapture (input) endpoints:\n");
    DeviceEnum::Print(DeviceEnum::List(eCapture));
    return 0;
  }

  if (cfg.probe)
  {
    std::printf("AC3 passthrough support (IsFormatSupported, exclusive):\n");
    for (const auto& e : DeviceEnum::List(eRender))
    {
      ComPtr<IMMDevice> d;
      if (!DeviceEnum::GetById(e.id, d))
        continue;
      bool ok48 = WasapiPassthrough::ProbeAc3(d.Get(), 48000);
      bool ok44 = WasapiPassthrough::ProbeAc3(d.Get(), 44100);
      std::printf("  %-48s %s  AC3@48k:%s  AC3@44.1k:%s\n", Narrow(e.name.c_str()).c_str(),
                  e.isSpdif ? "[SPDIF]" : "       ", ok48 ? "YES" : "no ", ok44 ? "YES" : "no ");
    }
    return 0;
  }

  SetConsoleCtrlHandler(CtrlHandler, TRUE);

  if (cfg.monitor)
  {
    ComPtr<IMMDevice> inDev;
    EndpointInfo inInfo;
    if (!ResolveCapture(cfg, inDev, inInfo))
      return 1;
    std::printf("Input   : %s %s\n", Narrow(inInfo.name.c_str()).c_str(),
                cfg.loopback ? "(loopback)" : "(capture)");
    return RunMonitor(cfg, inDev.Get());
  }

  // Keep exactly one persistent background engine. The switcher and --mode invocations return
  // above before creating this mutex, so they can coexist with the daemon.
  HANDLE singleton = CreateMutexW(nullptr, FALSE, L"Local\\VirtualAc3EncoderEngineV1");
  if (!singleton)
  {
    std::fprintf(stderr, "failed to create engine singleton mutex\n");
    return 1;
  }
  if (GetLastError() == ERROR_ALREADY_EXISTS)
  {
    std::fprintf(stderr, "another virtual-ac3-encoder engine is already running\n");
    CloseHandle(singleton);
    return 4;
  }

  std::atomic<RuntimeAudioMode> desired{RuntimeAudioMode::Surround};
  std::atomic<RuntimeAudioMode> current{RuntimeAudioMode::Starting};
  std::string lastError;
  std::mutex errorMutex;

  ModeControlServer control;
  if (!control.Start(&desired, &current, &lastError, &errorMutex))
  {
    std::fprintf(stderr, "[ModeControl] failed to start control server\n");
    CloseHandle(singleton);
    return 1;
  }

  std::printf("[ModeControl] ready: engine.exe --switcher | --mode surround|guitar|status\n");

  std::unique_ptr<RunningPipeline> pipeline;
  auto nextRetry = std::chrono::steady_clock::now();

  auto startTime = std::chrono::steady_clock::now();
  while (!g_stop.load())
  {
    const RuntimeAudioMode want = desired.load();
    const RuntimeAudioMode have = current.load();

    if (want == RuntimeAudioMode::Guitar)
    {
      if (have != RuntimeAudioMode::Guitar)
      {
        current.store(RuntimeAudioMode::Stopping);
        std::printf("[ModeControl] switching to GUITAR: releasing capture + exclusive S/PDIF\n");
        pipeline.reset();

        {
          std::lock_guard<std::mutex> lock(errorMutex);
          lastError.clear();
        }

        current.store(RuntimeAudioMode::Guitar);
        std::printf("[ModeControl] GUITAR active: S/PDIF is free for ASIO4ALL\n");
      }
    }
    else if (want == RuntimeAudioMode::Surround && have != RuntimeAudioMode::Surround)
    {
      const auto now = std::chrono::steady_clock::now();
      if (now >= nextRetry)
      {
        current.store(RuntimeAudioMode::Starting);
        std::printf("[ModeControl] switching to SURROUND: acquiring VB-CABLE + S/PDIF\n");

        std::string err;
        auto candidate = StartAudioPipeline(cfg, err);
        if (candidate)
        {
          pipeline = std::move(candidate);
          {
            std::lock_guard<std::mutex> lock(errorMutex);
            lastError.clear();
          }
          current.store(RuntimeAudioMode::Surround);
          std::printf("[ModeControl] SURROUND active\n");
        }
        else
        {
          pipeline.reset();
          {
            std::lock_guard<std::mutex> lock(errorMutex);
            lastError = err;
          }
          current.store(RuntimeAudioMode::Error);
          nextRetry = now + std::chrono::seconds(2);
          std::fprintf(stderr, "[ModeControl] surround start failed: %s; retrying in 2 s\n",
                       err.c_str());
        }
      }
    }

    std::this_thread::sleep_for(std::chrono::milliseconds(100));

    if (cfg.durationSeconds > 0 &&
        std::chrono::steady_clock::now() - startTime >= std::chrono::seconds(cfg.durationSeconds))
      break;
  }

  std::printf("\nStopping...\n");
  current.store(RuntimeAudioMode::Stopping);
  pipeline.reset();
  control.Stop();
  CloseHandle(singleton);
  return 0;
}
